/**
 * Glimmer Persona Page — the primary interactive workspace.
 *
 * REQ:GlimmerPersonaPage
 * REQ:VisualPersonaSupport
 * REQ:VisualPersonaAssetManagement
 * PLAN:WorkstreamE.PackageE12.PersonaPageConversationUi
 *
 * Layout (fills viewport below nav):
 * ┌──────────────────────────────────────────────────┐
 * │  Avatar  │   Chat Window          │  Controls    │  ← top section
 * │  (mood)  │   (conversation)       │  (gutter)    │
 * ├──────────┴────────────────────────┴──────────────┤
 * │              Workspace Canvas                     │  ← bottom section
 * │    (mind-map / portfolio cards / mode content)    │
 * └──────────────────────────────────────────────────┘
 *
 * Background: obsidian color cycle with soft glow orbs.
 * Avatar: mood-based, fades to "thinking" on user input.
 *
 * Conversation is backed by the persona session API — messages are
 * persisted and Glimmer replies are generated by the orchestration core.
 */

"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import {
  fetchGlimmerMood,
  createPersonaSession,
  fetchPersonaSession,
  sendPersonaMessage,
  submitPasteIn,
} from "@/lib/api-client";
import type {
  ChatMessage,
  InteractionMode,
  WorkspaceMode,
  GlimmerMood,
  PersonaSession,
} from "@/lib/types";

import { GlimmerAvatar } from "./glimmer-avatar";
import type { GlimmerMoodType } from "./glimmer-avatar";
import { ChatWindow } from "./chat-window";
import { ControlsGutter } from "./controls-gutter";
import { WorkspaceCanvas } from "./workspace-canvas";
import { useWorkingState } from "./use-working-state";

const SESSION_STORAGE_KEY = "glimmer-session-id";

function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

/** Convert backend PersonaMessage[] → ChatMessage[] for the UI. */
function sessionMessagesToChatMessages(
  session: PersonaSession,
): ChatMessage[] {
  return session.messages.map((m) => ({
    id: m.id,
    role: m.role as "user" | "glimmer",
    content: m.content,
    timestamp: m.created_at,
    mode: (m.workspace_mode as WorkspaceMode) || undefined,
  }));
}

export default function GlimmerPage() {
  // ── State ─────────────────────────────────────────────────────
  const [mood, setMood] = useState<GlimmerMoodType>("bau");
  const [moodReason, setMoodReason] = useState("Loading…");
  const [interactionMode, setInteractionMode] = useState<InteractionMode>("chat");
  const [workspaceMode, setWorkspaceMode] = useState<WorkspaceMode>("update");
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isThinking, setIsThinking] = useState(false);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [sessionError, setSessionError] = useState<string | null>(null);
  const sessionInitRef = useRef(false);
  /** True when session was restored from localStorage (not freshly created). */
  const [restoredSession, setRestoredSession] = useState(false);

  // ── E14: Working state for mind-map staged persistence ─────────
  const { nodes: workingNodes, edges: workingEdges, actions: workingStateActions } =
    useWorkingState(sessionId);

  // ── Load mood on mount ────────────────────────────────────────
  useEffect(() => {
    fetchGlimmerMood()
      .then((data: GlimmerMood) => {
        setMood(data.mood);
        setMoodReason(data.reason);
      })
      .catch(() => {
        setMood("bau");
        setMoodReason("Could not determine mood — business as usual");
      });
  }, []);

  // ── Restore or create session on mount ────────────────────────
  useEffect(() => {
    if (sessionInitRef.current) return;
    sessionInitRef.current = true;

    const makeWelcomeMessage = (mode: WorkspaceMode): ChatMessage => ({
      id: generateId(),
      role: "glimmer",
      content:
        "Hi! I'm Glimmer, your project chief-of-staff. What would you like to work on? You can switch modes in the controls panel, or just tell me what you need.",
      timestamp: new Date().toISOString(),
      mode,
    });

    /** Create a brand-new session and store it. */
    const createNewSession = (mode: WorkspaceMode) => {
      createPersonaSession(mode)
        .then((session: { id: string }) => {
          try { localStorage.setItem(SESSION_STORAGE_KEY, session.id); } catch { /* private browsing */ }
          setSessionId(session.id);
          setSessionError(null);
          setTimeout(() => setMessages([makeWelcomeMessage(mode)]), 400);
        })
        .catch((_err: unknown) => {
          setSessionError("Could not start a session — the backend may be unavailable.");
          console.error("Failed to create persona session:", _err);
        });
    };

    /** Try to restore from a previous session; fall back to creating new. */
    let storedId: string | null = null;
    try { storedId = localStorage.getItem(SESSION_STORAGE_KEY); } catch { /* private browsing */ }

    if (storedId) {
      fetchPersonaSession(storedId)
        .then((session: PersonaSession) => {
          if (session.session_status === "active" || session.session_status === "paused") {
            // ── Restore ──
            setSessionId(session.id);
            setSessionError(null);
            setRestoredSession(true);

            const restoredMode = (session.workspace_mode as WorkspaceMode) || "update";
            setWorkspaceMode(restoredMode);

            const restored = sessionMessagesToChatMessages(session);
            setMessages(restored.length > 0 ? restored : [makeWelcomeMessage(restoredMode)]);
          } else {
            // Terminal state — start fresh
            try { localStorage.removeItem(SESSION_STORAGE_KEY); } catch { /* */ }
            createNewSession(workspaceMode);
          }
        })
        .catch(() => {
          // Fetch failed (404, network error) — start fresh
          try { localStorage.removeItem(SESSION_STORAGE_KEY); } catch { /* */ }
          createNewSession(workspaceMode);
        });
    } else {
      createNewSession(workspaceMode);
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Auto-restore working state for recovered sessions ─────────
  useEffect(() => {
    if (restoredSession && sessionId) {
      workingStateActions.restoreFromBackup().catch(() => {
        /* best-effort — working state may simply be empty */
      });
      setRestoredSession(false);
    }
  }, [restoredSession, sessionId, workingStateActions]);

  // ── Handle user sending a message ─────────────────────────────
  const handleSendMessage = useCallback(
    async (content: string) => {
      // Check for mode-switch commands
      const lower = content.toLowerCase().trim();
      const modeMap: Record<string, WorkspaceMode> = {
        "idea mode": "idea",
        "plan mode": "plan",
        "report mode": "report",
        "debrief mode": "debrief",
        "update mode": "update",
        "switch to idea": "idea",
        "switch to plan": "plan",
        "switch to report": "report",
        "switch to debrief": "debrief",
        "switch to update": "update",
      };

      let currentMode = workspaceMode;
      for (const [trigger, mode] of Object.entries(modeMap)) {
        if (lower.includes(trigger)) {
          setWorkspaceMode(mode);
          currentMode = mode;
        }
      }

      // Add user message to chat immediately
      const userMsg: ChatMessage = {
        id: generateId(),
        role: "user",
        content,
        timestamp: new Date().toISOString(),
        mode: currentMode,
      };
      setMessages((prev) => [...prev, userMsg]);
      setIsThinking(true);

      // Send message to backend
      if (sessionId) {
        try {
          const reply = await sendPersonaMessage(
            sessionId,
            content,
            currentMode,
          );

          const glimmerMsg: ChatMessage = {
            id: reply.id,
            role: "glimmer",
            content: reply.content,
            timestamp: reply.created_at,
            mode: currentMode,
          };
          setMessages((prev) => [...prev, glimmerMsg]);
        } catch (err) {
          console.error("Failed to send message:", err);
          const errorMsg: ChatMessage = {
            id: generateId(),
            role: "glimmer",
            content:
              "I'm sorry, I couldn't process that right now. The backend may be experiencing issues. Please try again in a moment.",
            timestamp: new Date().toISOString(),
            mode: currentMode,
          };
          setMessages((prev) => [...prev, errorMsg]);
        }
      } else {
        // No session — show offline fallback
        const offlineMsg: ChatMessage = {
          id: generateId(),
          role: "glimmer",
          content:
            "I'm not connected to my reasoning engine right now. Please check that the backend is running and refresh.",
          timestamp: new Date().toISOString(),
          mode: currentMode,
        };
        setMessages((prev) => [...prev, offlineMsg]);
      }

      setIsThinking(false);
    },
    [workspaceMode, sessionId],
  );

  // ── Handle paste-in content submission ─────────────────────────
  const handlePasteIn = useCallback(
    async (content: string, contentTypeHint: string) => {
      if (!sessionId) return;

      // Show user paste-in summary in chat
      const preview = content.length > 120 ? content.slice(0, 120) + "…" : content;
      const userMsg: ChatMessage = {
        id: generateId(),
        role: "user",
        content: `📋 Pasted content (${contentTypeHint}):\n${preview}`,
        timestamp: new Date().toISOString(),
        mode: workspaceMode,
      };
      setMessages((prev) => [...prev, userMsg]);
      setIsThinking(true);

      try {
        const result = await submitPasteIn(sessionId, content, contentTypeHint);

        // Add extracted nodes to working state
        if (result.candidate_nodes.length > 0) {
          workingStateActions.addNodesFromPasteIn(result.candidate_nodes);
        }

        // Show Glimmer's explanation in chat
        const glimmerMsg: ChatMessage = {
          id: generateId(),
          role: "glimmer",
          content: result.explanation,
          timestamp: new Date().toISOString(),
          mode: workspaceMode,
        };
        setMessages((prev) => [...prev, glimmerMsg]);
      } catch (err) {
        console.error("Paste-in failed:", err);
        const errorMsg: ChatMessage = {
          id: generateId(),
          role: "glimmer",
          content:
            "I'm sorry, I couldn't process the pasted content right now. Please try again in a moment.",
          timestamp: new Date().toISOString(),
          mode: workspaceMode,
        };
        setMessages((prev) => [...prev, errorMsg]);
      }

      setIsThinking(false);
    },
    [sessionId, workspaceMode, workingStateActions],
  );

  // ── Render ────────────────────────────────────────────────────
  return (
    <div
      className="fixed inset-0 top-14 z-20 obsidian-bg flex flex-col overflow-hidden"
      data-testid="page-glimmer"
    >
      {/* Session error banner */}
      {sessionError && (
        <div className="mx-4 mt-2 px-4 py-2 rounded-xl bg-error/10 border border-error/20 text-error text-xs"
             data-testid="session-error">
          {sessionError}
        </div>
      )}

      {/* ── Top section: Avatar + Chat + Controls ─────────────── */}
      <div className="relative z-20 flex gap-4 p-4 h-[55%] min-h-[320px]">
        {/* Left: Avatar */}
        <div className="flex flex-col items-center justify-center w-[220px] shrink-0">
          <GlimmerAvatar mood={mood} isThinking={isThinking} />
          <div className="mt-3 text-center">
            <span className="text-xs font-bold text-primary font-headline tracking-wide">
              Glimmer
            </span>
            <p className="text-[10px] text-muted-light mt-0.5 capitalize">
              {workspaceMode} mode
            </p>
          </div>
        </div>

        {/* Center: Chat window */}
        <div className="flex-1 min-w-0">
          <ChatWindow
            messages={messages}
            interactionMode={interactionMode}
            isThinking={isThinking}
            onSendMessage={handleSendMessage}
            onPasteIn={handlePasteIn}
          />
        </div>

        {/* Right: Controls gutter */}
        <ControlsGutter
          interactionMode={interactionMode}
          workspaceMode={workspaceMode}
          mood={mood}
          moodReason={moodReason}
          onInteractionModeChange={setInteractionMode}
          onWorkspaceModeChange={setWorkspaceMode}
        />
      </div>

      {/* ── Bottom section: Workspace canvas ──────────────────── */}
      <div className="relative z-10 flex-1 min-h-0 px-4 pb-4">
        <WorkspaceCanvas
          mode={workspaceMode}
          workingNodes={workingNodes}
          workingEdges={workingEdges}
          workingStateActions={workingStateActions}
        />
      </div>
    </div>
  );
}


