"""add_source_layer_entities

Revision ID: 04f18b84875c
Revises: f45e9c073be9
Create Date: 2026-04-13 06:32:32.519382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04f18b84875c'
down_revision: Union[str, Sequence[str], None] = 'f45e9c073be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('account_label', sa.String(length=255), nullable=False),
    sa.Column('account_address', sa.String(length=512), nullable=True),
    sa.Column('tenant_context', sa.String(length=255), nullable=True),
    sa.Column('purpose_label', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('auth_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sync_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('profile_type', sa.String(length=50), nullable=False),
    sa.Column('profile_label', sa.String(length=255), nullable=False),
    sa.Column('profile_address', sa.String(length=512), nullable=True),
    sa.Column('profile_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connected_account_id', sa.UUID(), nullable=False),
    sa.Column('external_event_id', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description_summary', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_or_link', sa.String(length=1024), nullable=True),
    sa.Column('source_calendar', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connected_account_id', sa.UUID(), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connected_account_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('external_thread_id', sa.String(length=512), nullable=False),
    sa.Column('derived_subject', sa.String(length=512), nullable=True),
    sa.Column('participant_set', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connected_account_id', sa.UUID(), nullable=False),
    sa.Column('account_profile_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('external_message_id', sa.String(length=512), nullable=False),
    sa.Column('external_thread_id', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sender_identity', sa.String(length=512), nullable=True),
    sa.Column('recipient_identities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('import_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_profile_id'], ['account_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('message_threads')
    op.drop_table('imported_signals')
    op.drop_table('calendar_events')
    op.drop_table('account_profiles')
    op.drop_table('connected_accounts')
    # ### end Alembic commands ###
