"""add_research_and_expert_advice_tables

Revision ID: 1c7c7d6aa26a
Revises: cfb2c8fc249b
Create Date: 2026-04-14 07:07:33.999109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c7c7d6aa26a'
down_revision: Union[str, Sequence[str], None] = 'cfb2c8fc249b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_advice_exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invocation_origin', sa.String(length=50), nullable=False),
    sa.Column('triggering_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('gemini_mode', sa.String(length=20), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('review_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invocation_origin', sa.String(length=50), nullable=False),
    sa.Column('triggering_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('research_query', sa.Text(), nullable=False),
    sa.Column('document_name', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completion_signal', sa.String(length=50), nullable=True),
    sa.Column('document_url', sa.String(length=2048), nullable=True),
    sa.Column('document_renamed', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('finding_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence_signal', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_source_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_title', sa.String(length=1024), nullable=True),
    sa.Column('source_description', sa.Text(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relevance_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_summary_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('key_findings_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_project_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_summary_artifacts')
    op.drop_table('research_source_references')
    op.drop_table('research_findings')
    op.drop_table('research_runs')
    op.drop_table('expert_advice_exchanges')
    # ### end Alembic commands ###
