"""add_remaining_domain_entities

Revision ID: b04bfdd8469d
Revises: 04f18b84875c
Create Date: 2026-04-13 06:36:00.777007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b04bfdd8469d'
down_revision: Union[str, Sequence[str], None] = '04f18b84875c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('channel_identity', sa.String(length=255), nullable=True),
    sa.Column('session_state', sa.String(length=50), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_summary_id', sa.UUID(), nullable=True),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('focus_packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('top_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('high_risk_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('waiting_on_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reply_debt_summary', sa.Text(), nullable=True),
    sa.Column('calendar_pressure_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('asset_path', sa.String(length=1024), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocker_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('blocking_what', sa.Text(), nullable=True),
    sa.Column('owner_hint', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefing_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('linked_project_id', sa.UUID(), nullable=True),
    sa.Column('briefing_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_scope_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('decision_text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('source_record_type', sa.String(length=50), nullable=True),
    sa.Column('linked_project_id', sa.UUID(), nullable=True),
    sa.Column('linked_stakeholder_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=True),
    sa.Column('tone_mode', sa.String(length=50), nullable=True),
    sa.Column('body_content', sa.Text(), nullable=False),
    sa.Column('rationale_summary', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('intent_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('source_record_type', sa.String(length=50), nullable=False),
    sa.Column('linked_project_id', sa.UUID(), nullable=True),
    sa.Column('proposed_owner', sa.String(length=255), nullable=True),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('due_date_signal', sa.String(length=255), nullable=True),
    sa.Column('urgency_signal', sa.String(length=50), nullable=True),
    sa.Column('review_state', sa.String(length=50), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_deadline_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('source_record_type', sa.String(length=50), nullable=False),
    sa.Column('linked_project_id', sa.UUID(), nullable=True),
    sa.Column('deadline_text', sa.Text(), nullable=False),
    sa.Column('inferred_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_state', sa.String(length=50), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('source_record_type', sa.String(length=50), nullable=False),
    sa.Column('linked_project_id', sa.UUID(), nullable=True),
    sa.Column('decision_text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('review_state', sa.String(length=50), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('source_record_type', sa.String(length=50), nullable=False),
    sa.Column('candidate_project_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_project_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ambiguity_flag', sa.Boolean(), nullable=False),
    sa.Column('classification_rationale', sa.Text(), nullable=True),
    sa.Column('extracted_stakeholder_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_state', sa.String(length=50), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['selected_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('classification_type', sa.String(length=50), nullable=False),
    sa.Column('classification_value', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['persona_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_selection_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('interaction_context', sa.String(length=255), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['persona_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_scope_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version_marker', sa.Integer(), nullable=False),
    sa.Column('confidence_indicator', sa.Float(), nullable=True),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['project_summaries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('refresh_type', sa.String(length=100), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('input_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_artifact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity_signal', sa.String(length=50), nullable=True),
    sa.Column('likelihood_signal', sa.String(length=50), nullable=True),
    sa.Column('mitigation_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_conversation_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_session_id', sa.UUID(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=False),
    sa.Column('current_topic', sa.String(length=255), nullable=True),
    sa.Column('last_referenced_project_id', sa.UUID(), nullable=True),
    sa.Column('pending_clarification', sa.Text(), nullable=True),
    sa.Column('temporary_reply_mode', sa.String(length=50), nullable=True),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_session_id'], ['channel_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_referenced_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_session_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_session_id', sa.UUID(), nullable=False),
    sa.Column('transcript_content', sa.Text(), nullable=True),
    sa.Column('summary_content', sa.Text(), nullable=True),
    sa.Column('extracted_action_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['channel_session_id'], ['channel_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waiting_on_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('waiting_on_whom', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('variant_label', sa.String(length=100), nullable=False),
    sa.Column('body_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('workstream_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_hint', sa.String(length=255), nullable=True),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstream_id'], ['project_workstreams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_items')
    op.drop_table('draft_variants')
    op.drop_table('waiting_on_records')
    op.drop_table('voice_session_states')
    op.drop_table('telegram_conversation_states')
    op.drop_table('risk_records')
    op.drop_table('refresh_events')
    op.drop_table('project_summaries')
    op.drop_table('persona_selection_events')
    op.drop_table('persona_classifications')
    op.drop_table('message_classifications')
    op.drop_table('extracted_decisions')
    op.drop_table('extracted_deadline_signals')
    op.drop_table('extracted_actions')
    op.drop_table('drafts')
    op.drop_table('decision_records')
    op.drop_table('briefing_artifacts')
    op.drop_table('blocker_records')
    op.drop_table('persona_assets')
    op.drop_table('focus_packs')
    op.drop_table('channel_sessions')
    op.drop_table('audit_records')
    # ### end Alembic commands ###
