"""add_primary_operator_entity

Revision ID: cfb2c8fc249b
Revises: b04bfdd8469d
Create Date: 2026-04-13 10:45:42.025558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfb2c8fc249b'
down_revision: Union[str, Sequence[str], None] = 'b04bfdd8469d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('primary_operators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('preferred_timezone', sa.String(length=100), nullable=True),
    sa.Column('preferred_working_hours', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=True),
    sa.Column('tone_preferences', sa.Text(), nullable=True),
    sa.Column('channel_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('channel_sessions', sa.Column('operator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'channel_sessions', 'primary_operators', ['operator_id'], ['id'], ondelete='SET NULL')
    op.add_column('connected_accounts', sa.Column('operator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'connected_accounts', 'primary_operators', ['operator_id'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('operator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'primary_operators', ['operator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'operator_id')
    op.drop_constraint(None, 'connected_accounts', type_='foreignkey')
    op.drop_column('connected_accounts', 'operator_id')
    op.drop_constraint(None, 'channel_sessions', type_='foreignkey')
    op.drop_column('channel_sessions', 'operator_id')
    op.drop_table('primary_operators')
    # ### end Alembic commands ###
