"""add_stakeholder_entities

Revision ID: f45e9c073be9
Revises: 33f1e1085a52
Create Date: 2026-04-13 06:30:57.393170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45e9c073be9'
down_revision: Union[str, Sequence[str], None] = '33f1e1085a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('relationship_importance', sa.String(length=50), nullable=True),
    sa.Column('communication_style_hints', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stakeholder_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stakeholder_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('identity_value', sa.String(length=512), nullable=False),
    sa.Column('tenant_context', sa.String(length=255), nullable=True),
    sa.Column('verification_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stakeholder_project_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stakeholder_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('importance_within_project', sa.String(length=50), nullable=True),
    sa.Column('open_commitments', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stakeholder_project_links')
    op.drop_table('stakeholder_identities')
    op.drop_table('stakeholders')
    # ### end Alembic commands ###
